name = "TimeSeriesKit"
uuid = "e44ab2e3-975d-47c9-b14d-90d85588e1d2"
authors = ["Yannick Gibson <yannick.gibson@seznam.cz> and contributors"]
version = "1.0.0-DEV"

[compat]
Aqua = "0.8"
Test = "1.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
