name = "TimeSeriesKit"
uuid = "e44ab2e3-975d-47c9-b14d-90d85588e1d2"
authors = ["Yannick Gibson <yannick.gibson@seznam.cz> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
