name = "TimeSeriesKit"
uuid = "e44ab2e3-975d-47c9-b14d-90d85588e1d2"
authors = ["Yannick Gibson <yannick.gibson@seznam.cz> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extensions]
PlotsExt = ["Plots", "StatsBase"]

[compat]
Aqua = "0.8"
CSV = "0.10"
DataFrames = "1.8"
LinearAlgebra = "1.11"
Plots = "1"
Random = "1.11"
Statistics = "1.11"
StatsBase = "0.34"
Test = "1.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "Random"]
