name = "TimeSeriesKitExamples"
authors = ["Yannick Gibson <yannick.gibson@seznam.cz> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TimeSeriesKit = "e44ab2e3-975d-47c9-b14d-90d85588e1d2"

[compat]
julia = "1.11"
