name = "TimeSeriesKitExamples"
authors = ["Yannick Gibson <yannick.gibson@seznam.cz> and contributors"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeSeriesKit = "e44ab2e3-975d-47c9-b14d-90d85588e1d2"

[compat]
julia = "1.11"
